
import React, { useState, useEffect } from 'react';
import { WorkPersona, ImageSize, GeneratedImage } from '../types';
import { GoogleGenAI } from '@google/genai';
import { Sparkles, Loader2, Download, Maximize2, AlertCircle } from 'lucide-react';

// Access aistudio from window for mandatory API key selection as per guidelines
const aistudio = (window as any).aistudio;

export const ImageSandbox: React.FC<{ persona: WorkPersona }> = ({ persona }) => {
  const [prompt, setPrompt] = useState('');
  const [size, setSize] = useState<ImageSize>('1K');
  const [isGenerating, setIsGenerating] = useState(false);
  const [images, setImages] = useState<GeneratedImage[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [hasKey, setHasKey] = useState<boolean | null>(null);

  // Check for selected API key on mount for gemini-3-pro-image-preview
  useEffect(() => {
    const checkKey = async () => {
      if (aistudio && typeof aistudio.hasSelectedApiKey === 'function') {
        setHasKey(await aistudio.hasSelectedApiKey());
      } else {
        setHasKey(true);
      }
    };
    checkKey();
  }, []);

  // Open the key selection dialog and assume success as per guidelines to mitigate race condition
  const handleOpenKey = async () => {
    if (aistudio && typeof aistudio.openSelectKey === 'function') {
      await aistudio.openSelectKey();
      setHasKey(true);
    }
  };

  const handleGenerate = async () => {
    if (!prompt.trim() || isGenerating) return;

    // Double-check for API key selection before initiating call
    if (aistudio && typeof aistudio.hasSelectedApiKey === 'function') {
      const selected = await aistudio.hasSelectedApiKey();
      if (!selected) {
        if (typeof aistudio.openSelectKey === 'function') {
          await aistudio.openSelectKey();
          setHasKey(true);
          return;
        }
      }
    }

    setIsGenerating(true);
    setError(null);

    try {
      // Create a new instance right before the call to ensure the latest API key is used
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      const visualPrompt = `
        STYLE ALIGNED WITH PERSONA: ${persona.role} - ${persona.tone}
        CONTEXT: ${persona.knowledge}
        USER REQUEST: ${prompt}
        Visual aesthetic should be professional, sharp, and aligned with the persona context.
      `.trim();

      const response = await ai.models.generateContent({
        model: 'gemini-3-pro-image-preview',
        contents: {
          parts: [{ text: visualPrompt }]
        },
        config: {
          imageConfig: {
            aspectRatio: "1:1",
            imageSize: size
          }
        }
      });

      let foundImage = false;
      // Safeguard property access as per guidelines
      const candidates = response.candidates;
      if (candidates && candidates[0] && candidates[0].content && candidates[0].content.parts) {
        for (const part of candidates[0].content.parts) {
          if (part.inlineData) {
            const imageUrl = `data:image/png;base64,${part.inlineData.data}`;
            setImages(prev => [{
              url: imageUrl,
              prompt: prompt,
              size: size,
              timestamp: Date.now()
            }, ...prev]);
            foundImage = true;
            break;
          }
        }
      }

      if (!foundImage) setError('No image was generated by the model.');
      else setPrompt('');

    } catch (err: any) {
      console.error(err);
      // If the project doesn't have billing, reset key state as per guidelines
      if (err?.message?.includes("Requested entity was not found.")) {
        setHasKey(false);
        setError("Bitte wähle einen API-Key aus einem bezahlten Projekt aus.");
      } else {
        setError('Generation failed. Please ensure your environment is correctly configured.');
      }
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadImage = (url: string, filename: string) => {
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Render mandatory key selection state if needed
  if (hasKey === false) {
    return (
      <div className="p-8 max-w-2xl mx-auto mt-20 text-center animate-in fade-in duration-500">
        <div className="bg-white rounded-[2.5rem] shadow-2xl p-12 border-4 border-indigo-50 space-y-8">
          <div className="bg-indigo-100 w-20 h-20 rounded-full flex items-center justify-center mx-auto">
            <Sparkles className="w-10 h-10 text-indigo-600" />
          </div>
          <h2 className="text-3xl font-bold text-slate-800">API-Key erforderlich</h2>
          <p className="text-slate-600 text-lg">
            Für die Bildgenerierung mit dem Modell <strong>gemini-3-pro-image-preview</strong> musst du einen eigenen API-Key aus einem Projekt mit aktiver Abrechnung auswählen.
          </p>
          <div className="bg-amber-50 border border-amber-100 rounded-2xl p-4 text-amber-800 text-sm">
            Hinweis: Ein Projekt mit <a href="https://ai.google.dev/gemini-api/docs/billing" target="_blank" rel="noopener noreferrer" className="underline font-bold">Billing-Anbindung</a> ist erforderlich.
          </div>
          <button
            onClick={handleOpenKey}
            className="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-4 rounded-2xl text-xl transition-all shadow-xl shadow-indigo-100"
          >
            API-Key auswählen
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="p-8 max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500">
      <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6 space-y-6">
        <div className="space-y-2">
          <h2 className="text-xl font-bold flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-indigo-600" />
            Visual Counterpart Generator
          </h2>
          <p className="text-sm text-slate-500">
            Generate avatars, logos, or workspace visuals for <strong>{persona.name}</strong>.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div className="md:col-span-3">
            <input
              type="text"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="Describe the image (e.g., A professional avatar in a futuristic lab...)"
              className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-all"
            />
          </div>
          <div className="flex gap-2">
            {(['1K', '2K', '4K'] as ImageSize[]).map((s) => (
              <button
                key={s}
                onClick={() => setSize(s)}
                className={`flex-1 py-3 rounded-xl border font-medium transition-all ${
                  size === s 
                    ? 'bg-indigo-600 border-indigo-600 text-white shadow-md' 
                    : 'bg-white border-slate-200 text-slate-500 hover:border-indigo-300'
                }`}
              >
                {s}
              </button>
            ))}
          </div>
        </div>

        <button
          onClick={handleGenerate}
          disabled={isGenerating || !prompt.trim()}
          className="w-full bg-slate-900 hover:bg-black disabled:bg-slate-300 text-white font-bold py-4 rounded-xl transition-all flex items-center justify-center gap-3 shadow-xl"
        >
          {isGenerating ? (
            <>
              <Loader2 className="w-5 h-5 animate-spin" />
              Manifesting Visuals...
            </>
          ) : (
            <>
              <Sparkles className="w-5 h-5" />
              Generate Image
            </>
          )}
        </button>

        {error && (
          <div className="p-4 bg-rose-50 border border-rose-100 text-rose-600 rounded-xl text-sm flex items-center gap-2">
            <AlertCircle className="w-4 h-4" /> {error}
          </div>
        )}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {images.map((img, i) => (
          <div key={img.timestamp} className="group bg-white rounded-2xl overflow-hidden shadow-sm border border-slate-200 transition-all hover:shadow-xl hover:-translate-y-1">
            <div className="relative aspect-square bg-slate-100">
              <img src={img.url} alt={img.prompt} className="w-full h-full object-cover" />
              <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-3">
                <button 
                  onClick={() => downloadImage(img.url, `persona-${i}.png`)}
                  className="p-3 bg-white rounded-full text-slate-900 hover:scale-110 transition-transform shadow-lg"
                >
                  <Download className="w-5 h-5" />
                </button>
                <button className="p-3 bg-white rounded-full text-slate-900 hover:scale-110 transition-transform shadow-lg">
                  <Maximize2 className="w-5 h-5" />
                </button>
              </div>
              <div className="absolute top-3 left-3 px-2 py-1 bg-white/90 backdrop-blur rounded-md text-[10px] font-bold text-slate-700 shadow-sm uppercase">
                {img.size}
              </div>
            </div>
            <div className="p-4">
              <p className="text-xs font-medium text-slate-400 mb-1 uppercase tracking-wider">Prompt</p>
              <p className="text-sm text-slate-700 line-clamp-2 leading-relaxed">{img.prompt}</p>
            </div>
          </div>
        ))}

        {isGenerating && (
          <div className="aspect-square bg-slate-100 rounded-2xl border-2 border-dashed border-slate-200 flex flex-col items-center justify-center gap-3 text-slate-400 animate-pulse">
            <Loader2 className="w-8 h-8 animate-spin" />
            <span className="text-sm font-medium">Generating High Res...</span>
          </div>
        )}
      </div>
    </div>
  );
};
